### ISSUE TITLE
When I update to the latest Alpha version and select the stable version channel, the plug-in will prompt that the latest stable version is 2019.2.1, not selected

### ISSUE THREAD

**Issue by cary-rowen** [nvda-es/updateChannel#3]
As stated in the title.
I updated to the latest Alpha-24249, b7d202b7
Then I selected the stable version RC version and the Beta version in the combo box, and the plug-in detected 2019.2.1
The same is true if I only choose the stable version.

**Comment by jmdaweb** [comment]
Hi,
There's nothing we can do in the add-on to fix this, It's a NV Access server problem. I'll include @feerenrut in the conversation.

**Comment by jmdaweb** [comment]
CC @feerrenrut

**Comment by feerrenrut** [comment]
@jmdaweb Could you give more details here? For instance what you are sending to the server, and what you expect back?

**Comment by jmdaweb** [comment]
Hi @feerrenrut,
This add-on doesn't send any information itself to the server. It only changes the value of `versionInfo.updateVersionType` between snapshot:alpha, beta, stable or None, depending on the user's choice, so the user can select a channel and install the latest version of that channel by checking for NVDA updates.
When an user installs the latest alpha snapshot and wants to return to the stable or beta channels, the server offers version 2019.2.1. After installing that version and checking for updates again, the server offers the latest stable or beta version.
Regards.

**Comment by feerrenrut** [comment]
NVDA doesn't support this at the moment, the add-on will have to handle this. Asking for the latest version of stable and giving an alpha version number is non-sensical to the server. I suspect there are two issues:
- The alpha version number doesn't make sense in the context of asking for updates for stable or beta.
- There are no released versions of NVDA with a higher version number than alpha: EG 2022.1 is greater than 2021.3
